### ISSUE TITLE
Capture Recurrance?

### ISSUE THREAD

**Issue by MattMencel** [yvangodard/icalsync#1]
Hi @yvangodard ...

I have a great need for this and am really happy I found it.  In my testing last night with a calendar with a lot of recurring events in it, it looks like many of the future recurrences are missing.  Maybe all?

Is that a known issue with your tool?

I'm planning to do more testing and debugging with this next week so I may have more details then.

Thanks,

**Comment by yvangodard** [comment]
Hi,
This is in production for a few months on my server.
And I didn't get this error at any time.
Keep me informed of what you get to solve.
Yvan

**Comment by MattMencel** [comment]
Hi Yvan,

I forked this and have made some additions.  I fixed recurrence so it works...for me anyway.  Also ran into some bugs with attendees that I fixed.  I think I'm going to add a Logger so that the debug output goes to a logfile rather than stdout (or maybe both?).

I'll send a pull request next week sometime and you can decide if you want to use them or not.

Thanks,
Matt
